### PR TITLE
bugfix - renamed redisStore to store in session middleware init

### PR DESCRIPTION
**Pull request by joefitter**

### CODE REVIEW

**Comment by joefitter** [comment]
@easternbloc @JoeChapman @bendiggle @gxxm session fix

**Comment by JoeChapman** [comment]
@joefitter please add this bugfix as a ticket to the jira board.

**Comment by easternbloc** [comment]
happy to merge when it goes green

**Comment by joefitter** [comment]
can do - my general rule of thumb is if it takes more time to add a ticket to jira than fix the bug, then to just fix

**Comment by JoeChapman** [comment]
That's not my rule of thumb

**Comment by joefitter** [comment]
^ _that_ is my rule of thumb

**Comment by JoeChapman** [comment]
Thanks Joe: https://jira.digital.homeoffice.gov.uk/secure/RapidBoard.jspa?rapidView=124&projectKey=RTMD&view=planning&selectedIssue=RTMD-41

**Comment by JoeChapman** [comment]
hey @joefitter can I delete this branch?

**Comment by joefitter** [comment]
yes, this is the old branch before history was removed, I'll kill it

**Pull request closed without merging**
