### PR TITLE
RTMD-41 - use SO HOF

### PR DESCRIPTION
**Pull request by bendiggle**
* updated to use hof#so-master
* fixed path to frontend-toolkit for app.scss
* added i18n-lookup, reference the dependency in email service - this was removed from HOF
* removed travis caching, clean npm cache before install, rvm use 2.2.2
* updated controllers that called functions without passing res as an argument

### CODE REVIEW

**Comment by bendiggle** [comment]
@joefitter Any idea why the build is failing for node version 6?

**Comment by joefitter** [comment]
looking

**Comment by joefitter** [comment]
@bendiggle update node-sass to "^3.7.0"

**Comment by bendiggle** [comment]
All passing now. Cheers @joefitter! Can I get a thumbs up?
@JoeChapman @gxxm

**Comment by joefitter** [comment]
boom - that was a good guess ;) 👍 from me

**Comment by bendiggle** [comment]
@JoeChapman has told me to merge it. If anything breaks, we can blame him.

**Comment by joefitter** [comment]
tests were passing - that's good enough for me!

**Pull request merged**
