### PR TITLE
STG setup PR

### PR DESCRIPTION
**Pull request by James-Hovell**

### CODE REVIEW

**Comment by James-Hovell** [comment]
**What** - Added rotm-stg as a working staging environment

**Comment by James-Hovell** [comment]
**What** - Added rotm-stg as a working staging environment. The environment works through testing shown in this drone build from the step `TEST_deploy_to_stg` https://drone-gh.acp.homeoffice.gov.uk/UKHomeOffice/rotm/824

**Comment by SarahJaneLuff** [comment]
lgtm

**Review by SarahJaneLuff — APPROVED** [review]
lgtm

**Pull request merged**
