### PR TITLE
RTMD-44 - removed back links

### PR DESCRIPTION
**Pull request by joefitter**
* added backLink null to confirm step
* confirm controller redirects to /reports when no reports

### CODE REVIEW

**Comment by joefitter** [comment]
back link will be visible and broken until this PR is merged - https://github.com/UKHomeOffice/hof-controllers/pull/67

**Comment by JoeChapman** [comment]
LGTM, ^^ @easternbloc, @gxxm?

**Comment by gxxm** [comment]
:thumbsup: :thumbsup:

**Comment by JoeChapman** [comment]
@gxxm if you're the second person to ok it, you can merge it.

**Comment by gxxm** [comment]
@JoeChapman Just about to...but you beat me to it

**Pull request merged**
