### PR TITLE
bugfix - use npm@>=3.10.8 on drone

### PR DESCRIPTION
**Pull request by joefitter**
There is a memory leak with a previous version of request. This has been fixed and bumped in npm@>=3.10.8

### CODE REVIEW

**Comment by joefitter** [comment]
this is still broken - dont merge yet

**Comment by easternbloc** [comment]
@joefitter what we doing about this?

**Comment by JoeChapman** [comment]
@joefitter @joefitter

**Comment by easternbloc** [comment]
@joefitter can I close this?

**Pull request closed without merging**
