### PR TITLE
RTMD-39 - modified .dockerignore to remove unknown references.

### PR DESCRIPTION
**Pull request by gxxm**
Modified .dockerignore to remove unknown references. 

Added missing references
- node_modules
- public
- apps/*/translations/*/default.json
- LICENSE.md
- README.md
- CONTRIBUTING.md

### CODE REVIEW

**Comment by JoeChapman** [comment]
Failing due to an issue with a non-existent branch (so-master) is eslint-homeoffice-config @joefitter can you fix the issue with that repo and so-master branch?

**Comment by joefitter** [comment]
Undeleting branch for now, will need some more work to get hof#master bumped

**Comment by joefitter** [comment]
retriggered build

**Comment by JoeChapman** [comment]
cheers ears

**Pull request merged**
